# 系统异常

```js
try {
  const data  await = xxxx()
} catch (err) {
    console.log(err)
}
console.log(666); // 如果 catch 捕获了，console.log 这里是不是也不会执行了。经过认证会执行，但是如果有依赖请求的 data 的话，要把 console.log(666) 放进 try 模块。 
```


- xhr 请求异常